# Generated by Django 6.0 on 2025-12-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
